jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install

version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  build_app:
    jobs:
      - build
